spring.application.name=techstore
spring.datasource.url=jdbc:mysql://localhost:3306/techstore
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081


jwt.secret=
jwt.expiration=
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=


# =========================
# VNPay Sandbox
# =========================
payment.vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.return-url=http://localhost:8081/api/payments/vnpay/return
payment.vnpay.ipn-url=http://localhost:8081/api/payments/vnpay/ipn

payment.vnpay.tmn-code=
payment.vnpay.hash-secret=

payment.vnpay.version=2.1.0
payment.vnpay.command=pay
payment.vnpay.order-type=other
payment.vnpay.locale=vn
payment.vnpay.currency-code=VND
payment.vnpay.expire-minutes=15
payment.vnpay.time-zone=Asia/Ho_Chi_Minh
